name       : gloox
version    : 1.0.20
release    : 2
source     :
    - https://camaya.net/download/gloox-1.0.20.tar.bz2 : 0243086c0f4f0440d6d8e55705f83249a4463a1d75a034be42b5312e8886dea8
license    : GPL-3.0-or-later
component  : programming
summary    : Full-featured Jabber/XMPP client library, written in clean ANSI C++
description: |
    gloox is a rock-solid, full-featured Jabber/XMPP client library written in C++. It makes writing spec-compliant clients easy and allows for hassle-free integration of Jabber/XMPP functionality into existing applications.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libidn)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
