name       : gloox
version    : 1.0.24
release    : 6
source     :
    - https://camaya.net/download/gloox-1.0.24.tar.bz2 : ae1462be2a2eb8fe5cd054825143617c53c2c9c7195606cb5a5ba68c0f68f9c9
license    : GPL-3.0-or-later
component  : programming.library
homepage   : https://camaya.net/
summary    : Full-featured Jabber/XMPP client library, written in clean ANSI C++
description: |
    gloox is a rock-solid, full-featured Jabber/XMPP client library written in C++. It makes writing spec-compliant clients easy and allows for hassle-free integration of Jabber/XMPP functionality into existing applications.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
