name       : gloox
version    : 1.0.15
release    : 1
source     :
    - http://camaya.net/download/gloox-1.0.15.tar.bz2 : 31e1fe7c0aedc74bf9566c4de68244825df9fbc20eabee5214536b4e3beea311
license    : GPL-3.0
component  : programming
summary    : Full-featured Jabber/XMPP client library, written in clean ANSI C++.
description: |
    Full-featured Jabber/XMPP client library, written in clean ANSI C++.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libidn)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
